### ISSUE TITLE
Bokeh widget themes

### ISSUE THREAD

**Issue by JohnLunzer** [zoofIO/flexx#375]
There is a way to get Bokeh plots to take themes. 

[This call](https://github.com/zoofIO/flexx/blob/master/flexx/ui/widgets/_bokeh.py#L95) to `bokeh.embed.component` in the Bokeh widget takes a `theme` argument. The passed argument needs to be in the form of a `bokeh.themes.Theme` object which can take a filename (yaml file) or a dict ([see source for example](https://github.com/bokeh/bokeh/blob/master/examples/embed/embed_themed.py)) as an argument on instantiation. 

I wanted to take it upon myself to modify the code but I think I don't understand widget properties well enough. I tried to add a `theme` property by adding a new method with the `@event.prop` decorator but I can't get `_plot_components` method to recognize the `theme` value I pass into the `BokehWidget`. My modified example from the docs, passing a `theme` argument runs fine but the colors of the plots don't change.

Any guidance would be greatly appreciated.

Here is a "dark theme" for a yaml file:
```yaml
attrs:
    Figure:
        background_fill_color: '#1C1C1C'
        border_fill_color: '#1C1C1C'
        outline_line_color: '#444444'
    Axis:
        axis_line_color: "white"
        axis_label_text_color: "white"
        major_label_text_color: "white"
        major_tick_line_color: "white"
        minor_tick_line_color: "white"
        minor_tick_line_color: "white"
    Grid:
        grid_line_dash: [6, 4]
        grid_line_alpha: .3
    Title:
        text_color: "white"
    Legend:
        label_text_color: "white"
        background_fill_color: '#121212'
        background_fill_alpha: 0.6
```
